### ISSUE TITLE
Selector in class should be removed

### ISSUE THREAD

**Issue by pzoechner** [tailwindtoolbox/TailwindToolbox#2]
In the setup guide, it says 

`.btn:hover {
    @apply hover:bg-teal-dark
}`

The selector should be removed from the class, otherwise, it won't compile in my experience.

https://github.com/tailwindtoolbox/TailwindToolbox/blob/97da0d4e2e1b1cdec41a3d67addd6723b966ca2f/dist/setup.php#L265

**Comment by tailwindtoolbox** [comment]
Great catch! Thanks for the update
