### ISSUE TITLE
Invalid URLs

### ISSUE THREAD

**Issue by Stefaans** [tailwindtoolbox/TailwindToolbox#20]
I notice a couple of invalid URLs at https://www.tailwindtoolbox.com/tools where you duplicated the https:// parts. Examples near the bottom of the list:
```
<a href="https://https://tailwindgrids.com" class="no-underline hover:no-underline">...
<a href="https://https://tailwindgrids.com" class="no-underline hover:no-underline">...
```

**Comment by tailwindtoolbox** [comment]
Thanks @Stefaans , i've fixed that! 👍
