### ISSUE TITLE
Will this setup work with AOS in the pipeline?

### ISSUE THREAD

**Issue by MattAppleton** [tailwindtoolbox/TailwindToolbox#21]
Hi there - -I am using tailwinds + purgecss successfully thanks to your fantastic and helpful guide.

But - I am struggling to figure out why I am unable to reduce my aos.css as part of this workflow? If I have my .aos css file in the same place as my postcss.config.js can I somehow add/merge it to the build script (package.json)?

`"build:css": "postcss tailwind.config.css -o css-compiled/tailwind.min.css"`

or should my .aos css be dealt with as part of the plugin module in postcss.config.js as attempted here (this didn't result in any change so far!)

`module.exports = {
    plugins: [
        // require('postcss-import'),
        tailwindcss('tailwind.config.js'),
        cssnano({
            preset: 'default',
        }),
        purgecss({
            content: ['templates/**/*.twig'],
            **css: ['aos.css'],**
            extractors: [{
                extractor: TailwindExtractor,
                extensions: ["html", "js", "twig", "php", "vue"]
            }]
        }),
        autoprefixer
    ]
}`

**Comment by tailwindtoolbox** [comment]
Hey Matt,

I'm not a super expert when it comes to Javascript / post css - i just cobbled together a few bits together when i set it up for the first time :)

But i think you have two options:

1) Just copy the classes from aos.css into the tailwind.config.css 

2) According to: https://github.com/postcss/postcss-cli/issues/195

`cat tailwind.config.css aos.css | postcss > css-compiled/tailwind.min.css`

Give it a try and let me know how you get on! 👍 
(sorry on work laptop, so can't test it for you)

**Comment by tailwindtoolbox** [comment]
(here's the list of all commands for postcss-cli -> https://github.com/postcss/postcss-cli)

**Comment by MattAppleton** [comment]
Hi there, and thanks so much for helping. I did try this already
`cat tailwind.config.css aos.css | postcss > css-compiled/tailwind.min.css`

but that seems to **add** the entire aos.css file to my minified tailwind, in other words it doesn't do the purgecss magic! 

Confused...

**Comment by MattAppleton** [comment]
I am guessing it is because the aos classes present like this, perhaps I need to amend the extractor / formatting for purgecss?

`  body[data-aos-easing=ease-out-sine] [data-aos], [data-aos][data-aos][data-aos-easing=ease-out-sine] {
    transition-timing-function: cubic-bezier(0.39, 0.575, 0.565, 1);
  }`

**Comment by MattAppleton** [comment]
Same thing happens if I append aos.css content into my tailwind.config.css. My build command just gives me the entire aos.css content and dent remove unused classes.

**Comment by tailwindtoolbox** [comment]
Yeah I think you will probably have to play with the extractor. 

Check my one out, see if you can add the path for the aos.css in content?

https://github.com/tailwindtoolbox/TailwindToolbox/blob/master/postcss.config.js

**Comment by MattAppleton** [comment]
hmmm... no joy so far, will have to carry on with this later, but many thanks for your help!

**Comment by tailwindtoolbox** [comment]
It seems data attributes don't work with purge css (https://github.com/FullHuman/purgecss/issues/110)

but it's in progress (https://github.com/FullHuman/purgecss/projects/2#card-28469951)

Perhaps just pull out the classes you are intending on using and pop them into your tailwind css file?
