### ISSUE TITLE
Additional content: hugo-landing-page

### ISSUE THREAD

**Issue by ttntm** [tailwindtoolbox/TailwindToolbox#24]
Hi, just stopping by to let you know about a simple landing page built with Hugo and Tailwind CSS that I published recently.

I'd appreciate it if you could add that to the (fantastic!) collection of resources you have on your site 😃 

A live demo can be found here: https://awesome.ttntm.me

**Comment by tailwindtoolbox** [comment]
Hi Tom, Great work!
I've added it to the templates!
Let me know if you create anything else, I'd love to add it!

(best to reach out to me on twitter (@amritnagi), i'm rarely on here and i don't seem to get any notifications!!)

**Comment by ttntm** [comment]
Thanks, I'll keep that in mind for the future.
