### ISSUE TITLE
Ghostwind home redirect on ghostwind page

### ISSUE THREAD

**Issue by Mikaleb** [tailwindtoolbox/TailwindToolbox#28]
https://www.tailwindtoolbox.com/starter-templates -> blog -> click on ghostwind home -> redirect on https://www.tailwindtoolbox.com/templates/ghostwind instead of https://www.tailwindtoolbox.com/templates/ghostwind-home

**Comment by tailwindtoolbox** [comment]
Good spot... thanks @Mikaleb
Fixed now!
