### ISSUE TITLE
Make links to products or pages outside the main page open new tabs

### ISSUE THREAD

**Issue by RomanFama592** [tailwindtoolbox/TailwindToolbox#39]
These two properties would have to be added to each tag "a": `target="_blank" rel="noopener noreferrer"`

> This change, which may seem minimal, would make the visit of the user who is browsing the page more retained, and would also make it more comfortable.

**Comment by amritnagi** [comment]
good shout, will make this change later! thanks!

**Comment by tailwindtoolbox** [comment]
All done! :)

**Comment by RomanFama592** [comment]
what a good service! ja ja
